### ISSUE TITLE
전반적인 메모

### ISSUE THREAD

**Issue by skang29** [TintypeMolly/yonsei_eng_vote_regulation#9]
공선관위를 하면서 전반적으로 느꼈던 것들 중 세칙에 넣었으면 하는 것들을 적어보겠습니다.
1. 공선관위가 관리하는 홈페이지, 주로 네이버 카페를 공식적으로 세칙에 명문화하여 실질적인 파워를 넣고 싶습니다.
2.  세칙에 공선관위가 사용한 예산 또한 결산공개를 하도록 명문화하고 싶습니다.
3. 공선관위의 업무시간을 제한하고 싶습니다. 보통 중앙 선거의 경우, 선관위가 24시간 동안 선관위실에 상주하여 선본과 여러 안건을 처리합니다. 하지만 공선관위의 경우 공과대학 건물 출입 제한 등과 같은 여러 이유로 공선관위가 실질적으로 선본과 어떠한 논의를 하고 결론을 내기 위하여 충분한 인원이 공선관위실에 상주할 수 없습니다. 따라서 오후10시부터 익일 오전 8시까지는 공선관위 업무를 하지 않는다 등을 넣었으면 좋겠습니다.
4. 과반선거관리위원회와 과반선거관리위원장을 명문화하고 싶습니다. 공과대학 학생회 선거의 경우 관례적으로 과반선거를 공선관위가 대리하여 진행하였는데 이런 일들이 상당히 큰 노력이 들어갑니다. 과반선거관리위원회 또한 각 과반의 선거에 책임감을 가지고 자주적으로 활동할 수 있도록 명문화하고 싶습니다. 공과대학 학생회 선거와는 관계없다고 볼 수도 있지만 공과대학선거관리위원회는 과반선거관리위원회의 상위 조직이기에, 그리고 실질적인 실무를 담당하기에 충분히 논의해볼 가치가 있다고 봅니다.
5. 시행세칙 협의모임의 안건지, 회의록, 속기 또는 녹취에 대한 내용을 명문화하여 어느 정도의 강제성을 가하는 것이 필요하다고 생각합니다.

아래에는 그 때 보내드렸던 카톡 복붙하여 적습니다.

9조 3호 : 접수받을 수 없다 -> 접수하지 않는다. 그리고 24시보다는 익일 오전10시가 더 타당하다고 생각합니다. 공선관위의 실수로 미비 서류가 접수되었을 경우에 대한 조항이 빠졌네요.

4장 12조 3호 : 선본은 공선관위 이외의 기관에 공선관위의 판결에 대한 이의를 제기할 수 없다. 단, 공선관위의 결정에 불복할 경우 이의를 제기하여 판결의 중선관위 이관을 요청할 수 있다.
5장 13조 : 문법
5장 14조 : 선관위원, 공선관위 통일
5장 14조 1호 : 피선거권이 없다. 제한한다는 뭔가 이상하지 않나요?
5장 14조 4호 : 말이 이상함
5장 15조 8호 : 상정이나 이월 외에 다른 단어를 찾아봐야 할 것 같아요
5장 15조 9호 : 맡길 수 있다 -> 이관할 수 있다. 그리고 판단 보다는 판결이라는 단어가 더 맞지 않나 싶네요.
5장 16조 1호 : 중선관위 내용이 빠졌습니다. 중앙이 관리하는 것도.
5장 16조 2호 : 공선관위나 공선관위원 -> 뭐가 다를까요. 오히려 공선관위만 쓰는게 나을 것 같기도.

그리고 벌칙이라는 말을 세칙에 사용하기에는 좋지 않은 단어 같습니다.

16조는 전체적으로 다 논의를 해서 손을 봐야할 것 같아요. 내용은 전달이 되는데 말이 조금 매끄럽지 않아요

6장 17조 : 시행세칙 협의모임은 공선관위와 각 선본의 선본장, 혹은 공선관위에서 지정한 그에 준하는 이들로 구성한다.
-> 제0차 시행세칙 협의모임의 경우 선본이 꾸려지기 전, 즉 후보자 등록을 하기 전에 모이기 때문에 선본장에 준하는 인물이라는 단서조항이 필요합니다.

6장 18조 2호 : 판단 -> 유권해석
6장 18조 5호 : 소집된다->소집한다
6장 18조 7호 : 이거는 원문 자체를 수정했어야 하는 내용이어서 적습니다.
시행세칙 협의모임에서 각 선본별 주 게시판을 배정하고 선거운동본부 사무실을 인준한다.
-> 이유가 뭐냐하면 공선관위가 공간을 마련해서 주는 것이 아니라, 알아서 공간을 정해서 가져오면 인준을 해주는 방식을 연례적으로 사용해왔습니다.

7장 19조 1호 : 공과대 재적생 -> 공과대학 재적생. 공과대 선거 참관인 -> 공과대학 선거 참관인
7장 20조 3호 : 시행세칙 협의모임이 허가한 범위 -> 흠... 애매한 것 같아요. 논의를 해봅시다.

7장 21조 2호 : 명찰에는 해당 선본의 이름과 참관인 본인의 이름을 적는다. -> 관례적으로 이렇게 해왔습니다.
7장 21조 3호 : 원본도 이상하네요. : 참관인이 투표구 내에서 부정행위를 할 경우, 공선관위원과 다른 선본 측 참관인이 만장일치로 인정할 시에 공선관위는 참관인의 퇴장을 명하고 이에 대한 어떠한 이의도 제기할 수 없다. 또한, 부정행위의 경중에 따라 공선관위는 해당 참관인이 소속한 선본에 주의 및 경고조치를 취할 수 있다.
7장 22조 4호 : 중선관위 -> 공선관위
7장 22조 5항 : 참관인은 본인이 투표할 때를 제외하고 투표구 내에 들어갈 수 없고, 의도적으로 투표구 주변에 있는 것을 금지한다.

8장 24조 : 가. 강의실 유세 / 나. 대중유세  이런식으로 가면 어떨까요

8장 25조 1호 : 시간 관련해서 부칙 보라고 하는 내용 필요합니다. 그리고 추가적인 선거운동 시간에 대한 제한요건도 넣어야 할 것 같아요.
8장 25조 3호 : 선전전 -> 선거운동

8장 25조 추가 호 : 중앙선거관리위원회에서 중앙선거의 합동유세, 정책토론회 혹은 이에 준하는 선거운동을 사유로 공선관위에 공과대학생회 선거운동의 제한을 요청할 경우 공선관위의 논의를 통해 선거운동 제한시간을 제한 시작시간 24시간 전에 공고하고 그 시간동안의 선거운동을 금지한다.

26조 2호 : 강의실 유세 -> 선거운동이 아니므로 유세는 잘못된 어휘 같아요. 원본 자체가 잘못되었네요.
26조에 정후보, 부후보 예정자가 언급할 수 있는 내용과, 선거운동본부원 예정자가 언급할 수 있는 내용을 구분하는 항목도 필요합니다.

27조 4호 : 출마기 -> 출마하기

27조 : 사퇴자에 관련한 내용이 없습니다.

29조 : 생회나 언론기관의 특정 후보에 대한 지지나 비방이 있을 경우, 이로 인해 피해를 입은 선본은 공선관위에 이의를 제기할 수 있으며, 공선관위는 심의를 거쳐 각 단체에 제재를 가할 수 있다. 또한 이로 인해 특정후보에게 유리한 상황이 전개될 경우에는 공선관위에서 심의하여 경고 조치를 취할 수 있다.
요 내용 빠졌네요

32조 : 시행세칙 협의모임에서 논의하고 -> 이건 빠져야 할 것 같습니다. 공선관위에서 논의를 하고 필요에 의해 시행세칙 협의모임을 소집하는 것이라서요.

33조 7호 : 인증 -> 검인

35조 2호 : 말로 하는 선거운동, 강의실 유세, 정책 토론회, 합동유세 등에서 "선본 XXX는 201X년 X월 XX일 X시 경 강의실 유세에서 XXX와 관련하여 허위사실을 유포하였음을 고지하고 이에 대해 사과의 말씀을 드립니다." 라고 하는거에요.

24조 3호 : 고려해 -> 따져 또는 경중에 따라

36조 1호 : 투표하지 않는다 보다는 제외한다가 낫지 않나 싶어요
36조 2호 : 1호에 언급하여 토, 일 언급 안 해도 될 것 같습니다. 그리고 국제캠퍼스의 경우 변동될 수 있으니 관련 조항이 필요해요.
36조 3호 : 투표연장은 부칙으로 넣기에는 중요한 사항이라 아예 여기에 명시하는 것이 좋습니다. 그리고 투표연장 논의는 시행세칙 협의모임에서 하지 않고 공선관위에서 해요.

37조 4호 : 총학생회 투표구 옆 으로 바꾸면 좋겠어요
37조 : 투표구 지정에 중앙선거관리위원회에서 지정하는 단과대학 학생회 선거 투표함 도 추가해야 할 것 같아요

39조 1호 : 확인하는 방식으로 한다 -> 확인한다.
39조 2호 : 여러 회 투표를 하거나 / 자격박탈조항 삭제한 이유가?

41조 2호 : 투표자는 신분증명서(학생증, 도서대출증, 재학증명서, 등록금 영수증)를 제시하고 선관위원이 명부를 확인한다.
추가 호 : 공선관위원은 공선관위 인준 도장을 투표용지에 날인한 후 참관인의 확인을 받은 뒤 투표자에게 투표용지를 배부한다.
추가 호 : 투표자는 도장이 날인된 투표용지를 받아 투표한다.

43조 3호 : 중선관위 -> 공선관위

9장의 경우 전체 선거권자 수 관련한 조항이 필요합니다. 49조 2호에 있기는 한데, 저기 있을 놈이 아닌 것 같고, 졸업 예정자와 함께 초과학기자도 포함이 되었던 것 같아서 다시 확인해볼 필요가 있습니다. 제가 시스템 짤 때에는 8학기 이상인 경우 뺀 것으로 알아요.

45조 : 단서조항 하나가 필요한데 논의를 해야 할 것 같아요. 원래 과반개표가 모두 종료된 후, 공과대학생회 선거 개표를 시작해야하는데 그 조항이 없네요.

46조 1호 : 공과대학생회 선거는 투표 종료일 당일에 개표한다.

48조 2호 : 오차의 계산은 다음과 같이 한다. 각 투표함별로 확인된 명부상의 투표자수와 각 투표함별로 확인된 실제 투표자수의 차(절대값)와 이중투표 및 대리투표로 확인된 수의 총합. 오차율의 계산은 다음과 같이 한다. 오차 / 전체 선거권자 수 x 100 (%)

49조 1호 : 단독선거의 경우 투표율이 40%를 넘지 않는 경우 재선거를 진행하지 않고 선거를 무산한다.
49조 추가 호 : 오차가 5% 이상인 경우

제51조 경고 -> 주의 및 경고 로 바꾸거나 제재로 가는 것이 좋을 것 같아요

51조 5호 : 위해한 단어 그대로 가져갔으면 좋겠어요

부칙

4조 자료집 : 사실 제출 못 하면 선거활동 등록 자체가 불가능해서 이거 고쳐야 할 것 같아요.

중형선전물 1 : 규격 가로x세로 636 x 1878mm
#### 추가

제5장 제14조 제한 및 의무 에 추가 하나만 하면 좋을 것 같아요
공선관위는 공과대학 학생회 선거활동 실무에 사용한 모든 서류를 해당 당선후보의 임기동안 보관할 의무가 있다.
공선관위는 개표한 표를 각 투표구 별로 각 선본 별, 무효표로 분류하여 해당 당선후보의 임기동안 보관할 의무가 있다.
위 두 문서는 공선관위가 모두 입회한 자리에서 봉인하고 날인하여 보관한다. 이런 식? 졸려서 말이 이상하네.

**Comment by TintypeMolly** [comment]
너무 많은게 다 적혀있어서 닫습니다. 이슈 이렇게 포괄적으로 쓰면 안돼요.
